---
apiVersion: v1
kind: Namespace
metadata:
  name: middleware

---

apiVersion: apps/v1
kind: statusfulset
metadata:
  labels:
    app: pgsql
  name: pgsql
  namespace: middleware
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgsql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASS
          value: password-postgres
        - name: REPLICATION_USER
          value: rbackup
        - name: REPLICATION_PASS
          value: password-backup
        - name: DEFAULT_ENCODING
          value: UTF8
        - name: POSTGRES_DBNAME
          value: postgres,database
        - name: POSTGRES_MULTIPLE_EXTENSIONS
          value: postgis,hstore
        - name: MAX_CONNECTIONS
          value: "2000"
        - name: PG_WAL_KEEP_SEGMENTS
          value: "100"
        - name: PG_WORK_MEM 
          value: "524kB"
        - name: PG_SHARED_BUFFERS 
          value: "2GB"
        - name: PG_EFFECTIVE_CACHE_SIZE 
          value: "6GB"
        - name: PG_MAINTAINANCE_WORK_MEM 
          value: "512MB"
        - name: LOGGING_COLLECTOR
          value: "off"
        - name: LOG_DIRECTORY
          value: "pg_log"
        - name: LOG_FILENAME
          value: "postgresql-%Y-%m-%d_%H%M%S.log"
        - name: LOG_ROTATION_AGE
          value: "1d"
        - name: LOG_ROTATION_SIZE
          value: "100MB"
        - name: LOG_TRUNCATE_ON_ROTATION
          value: "on"
        - name: LOG_LOCK_WAITS
          value: "on"
        - name: LOG_DURATION
          value: "on"
        - name: LOG_STATEMENT
          value: "all"
        - name: LOG_MIN_DURATION_STATEMENT
          value: "20"
        - name: LOG_CONNECTIONS
          value: "on"
        - name: LOG_DISCONNECTS
          value: "on"
        - name: LOG_LINE_PREFIX
          value: "%m [%p]: [%l-1] %u@%d "
        - name: LOG_TIMEZONE
          value: "Etc/UTC"
        image: images.docker.com/pgsql-gis-withlog:latest
        imagePullPolicy: IfNotPresent
        name: postgis
        resources:
          limits:
            cpu: "8"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        - mountPath: /data/backup
          name: backup
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/pgsql/data
          type: DirectoryOrCreate
        name: data
      - hostPath:
          path: /data/pgsql_backup
          type: DirectoryOrCreate
        name: backup

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: middleware
spec:
  ports:
  - name: 5432-5432
    nodePort: 25434
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pgsql
  type: NodePort

